// <auto-generated />
using System;
using CrumbsBookLoans.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrumbsBookLoans.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507020957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("CrumbsBookLoans.Api.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Borrower")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            Isbn = "978-0132350884",
                            LoanStatus = 0,
                            Owner = "Alice",
                            PublishedDate = new DateOnly(2008, 8, 1),
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "David Thomas",
                            Isbn = "978-0135957059",
                            LoanStatus = 0,
                            Owner = "Bob",
                            PublishedDate = new DateOnly(2019, 9, 23),
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Gang of Four",
                            Borrower = "Dave",
                            Isbn = "978-0201633610",
                            LoanStatus = 1,
                            Owner = "Charlie",
                            PublishedDate = new DateOnly(1994, 10, 31),
                            Title = "Design Patterns"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
