// <auto-generated />
using System;
using CrumbsBookLoans.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrumbsBookLoans.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("CrumbsBookLoans.Api.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Borrower")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoanStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "C.J. Cherryh",
                            Isbn = "978-0879977382",
                            LoanStatus = 0,
                            Owner = "Rob",
                            PublishedDate = new DateOnly(1981, 9, 1),
                            Title = "Downbelow Station"
                        },
                        new
                        {
                            Id = 2,
                            Author = "C.J. Cherryh",
                            Borrower = "Lukey",
                            Isbn = "978-0446364638",
                            LoanStatus = 1,
                            Owner = "Jess",
                            PublishedDate = new DateOnly(1988, 6, 1),
                            Title = "Cyteen"
                        },
                        new
                        {
                            Id = 3,
                            Author = "C.J. Cherryh",
                            Isbn = "978-0886776107",
                            LoanStatus = 0,
                            Owner = "Geordie",
                            PublishedDate = new DateOnly(1994, 1, 1),
                            Title = "Foreigner"
                        },
                        new
                        {
                            Id = 4,
                            Author = "C.J. Cherryh",
                            Isbn = "978-0879977542",
                            LoanStatus = 0,
                            Owner = "Damo",
                            PublishedDate = new DateOnly(1982, 6, 1),
                            Title = "The Pride of Chanur"
                        },
                        new
                        {
                            Id = 5,
                            Author = "C.J. Cherryh",
                            Borrower = "Liam",
                            Isbn = "978-0879977252",
                            LoanStatus = 1,
                            Owner = "Lukey",
                            PublishedDate = new DateOnly(1976, 1, 1),
                            Title = "Gate of Ivrel"
                        },
                        new
                        {
                            Id = 6,
                            Author = "C.J. Cherryh",
                            Isbn = "978-0879977153",
                            LoanStatus = 0,
                            Owner = "Liam",
                            PublishedDate = new DateOnly(1980, 1, 1),
                            Title = "Serpent's Reach"
                        },
                        new
                        {
                            Id = 7,
                            Author = "C.J. Cherryh",
                            Isbn = "978-0879977566",
                            LoanStatus = 0,
                            Owner = "David",
                            PublishedDate = new DateOnly(1982, 1, 1),
                            Title = "Merchanter's Luck"
                        },
                        new
                        {
                            Id = 8,
                            Author = "C.J. Cherryh",
                            Borrower = "Rob",
                            Isbn = "978-0446364621",
                            LoanStatus = 1,
                            Owner = "Bill",
                            PublishedDate = new DateOnly(1989, 1, 1),
                            Title = "Rimrunners"
                        },
                        new
                        {
                            Id = 9,
                            Author = "C.J. Cherryh",
                            Isbn = "978-0446364614",
                            LoanStatus = 0,
                            Owner = "Dave",
                            PublishedDate = new DateOnly(1991, 1, 1),
                            Title = "Heavy Time"
                        },
                        new
                        {
                            Id = 10,
                            Author = "C.J. Cherryh",
                            Isbn = "978-0879977016",
                            LoanStatus = 0,
                            Owner = "Hana",
                            PublishedDate = new DateOnly(1976, 1, 1),
                            Title = "Brothers of Earth"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Diana Wynne Jones",
                            Isbn = "978-0061447242",
                            LoanStatus = 0,
                            Owner = "Rob",
                            PublishedDate = new DateOnly(1986, 4, 1),
                            Title = "Howl's Moving Castle"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Diana Wynne Jones",
                            Borrower = "Geordie",
                            Isbn = "978-0064473897",
                            LoanStatus = 1,
                            Owner = "Jess",
                            PublishedDate = new DateOnly(1984, 9, 1),
                            Title = "Fire and Hemlock"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Diana Wynne Jones",
                            Isbn = "978-0061479946",
                            LoanStatus = 0,
                            Owner = "Geordie",
                            PublishedDate = new DateOnly(1977, 5, 1),
                            Title = "Charmed Life"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Diana Wynne Jones",
                            Isbn = "978-0064473941",
                            LoanStatus = 0,
                            Owner = "Damo",
                            PublishedDate = new DateOnly(1988, 1, 1),
                            Title = "The Lives of Christopher Chant"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Diana Wynne Jones",
                            Isbn = "978-0064473934",
                            LoanStatus = 0,
                            Owner = "Lukey",
                            PublishedDate = new DateOnly(1982, 1, 1),
                            Title = "Witch Week"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Diana Wynne Jones",
                            Borrower = "David",
                            Isbn = "978-0064473927",
                            LoanStatus = 1,
                            Owner = "Liam",
                            PublishedDate = new DateOnly(1980, 1, 1),
                            Title = "The Magicians of Caprona"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Diana Wynne Jones",
                            Isbn = "978-0061447259",
                            LoanStatus = 0,
                            Owner = "David",
                            PublishedDate = new DateOnly(1990, 1, 1),
                            Title = "Castle in the Air"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Diana Wynne Jones",
                            Isbn = "978-0061020261",
                            LoanStatus = 0,
                            Owner = "Bill",
                            PublishedDate = new DateOnly(1997, 1, 1),
                            Title = "Deep Secret"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Diana Wynne Jones",
                            Isbn = "978-0064407588",
                            LoanStatus = 0,
                            Owner = "Dave",
                            PublishedDate = new DateOnly(1987, 1, 1),
                            Title = "A Tale of Time City"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Diana Wynne Jones",
                            Borrower = "Rob",
                            Isbn = "978-0064473880",
                            LoanStatus = 1,
                            Owner = "Hana",
                            PublishedDate = new DateOnly(1975, 1, 1),
                            Title = "Dogsbody"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Bob Shaw",
                            Isbn = "978-0575016972",
                            LoanStatus = 0,
                            Owner = "Rob",
                            PublishedDate = new DateOnly(1972, 1, 1),
                            Title = "Other Days, Other Eyes"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Bob Shaw",
                            Isbn = "978-0575018297",
                            LoanStatus = 0,
                            Owner = "Jess",
                            PublishedDate = new DateOnly(1975, 1, 1),
                            Title = "Orbitsville"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Bob Shaw",
                            Borrower = "Damo",
                            Isbn = "978-0575038233",
                            LoanStatus = 1,
                            Owner = "Geordie",
                            PublishedDate = new DateOnly(1986, 1, 1),
                            Title = "The Ragged Astronauts"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Bob Shaw",
                            Isbn = "978-0575016965",
                            LoanStatus = 0,
                            Owner = "Damo",
                            PublishedDate = new DateOnly(1967, 1, 1),
                            Title = "Night Walk"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Bob Shaw",
                            Isbn = "978-0575016958",
                            LoanStatus = 0,
                            Owner = "Lukey",
                            PublishedDate = new DateOnly(1968, 1, 1),
                            Title = "The Two-Timers"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Bob Shaw",
                            Borrower = "Bill",
                            Isbn = "978-0575021617",
                            LoanStatus = 1,
                            Owner = "Liam",
                            PublishedDate = new DateOnly(1976, 1, 1),
                            Title = "A Wreath of Stars"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Bob Shaw",
                            Isbn = "978-0575024359",
                            LoanStatus = 0,
                            Owner = "David",
                            PublishedDate = new DateOnly(1977, 1, 1),
                            Title = "Who Goes Here?"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Bob Shaw",
                            Isbn = "978-0575033634",
                            LoanStatus = 0,
                            Owner = "Bill",
                            PublishedDate = new DateOnly(1983, 1, 1),
                            Title = "Orbitsville Departure"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Bob Shaw",
                            Isbn = "978-0575042100",
                            LoanStatus = 0,
                            Owner = "Dave",
                            PublishedDate = new DateOnly(1988, 1, 1),
                            Title = "The Wooden Spaceships"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Bob Shaw",
                            Isbn = "978-0575025523",
                            LoanStatus = 0,
                            Owner = "Hana",
                            PublishedDate = new DateOnly(1978, 1, 1),
                            Title = "Vertigo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
